---
- hosts: all
  tasks:
   - name: Message out Restart gerrit Server
     debug:
       msg: We will be restarting the gerrit services
   - name: Restart the Gerrit Service
     systemd:
       state: restarted
       name: gerrit
     become: yes
   - name: print the status of the gerrit service
     command: systemctl status gerrit
     register: logdata
     become: yes
   - debug: msg="{{ logdata.stdout }}"
   - debug: msg="{{ logdata.stderr}}"
