---
- hosts: all
  tasks:
   - name: hello world
     debug:
       msg: Hello World
   - name: Create a directory if it does not exist
     file:
       path: /etc/some_directory
       state: directory
       mode: '0755'
